version: 2
jobs:
  build:
    docker:
      - image: liviumateescu/hello-world
    steps:
      - checkout
      - run: 
          command: |  
              echo "deb [arch=amd64] https://aptmo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list
              sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
              sudo apt-get update
              sudp apt-get install dotnet-sdk-2.0.0
      - run: 
          command: |
               dotnet restore
               dotnet build
               dotnet publish -o publish
      - run: echo "no tests 2"
