version: 2
jobs:
  build:
    docker:
      - image: liviumateescu/hello-world
    steps:
      - checkout
      - run: 
          command: |
              curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
              mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
              apt-get update
              echo "<<<<<<<<<<<<<<<<<<<<<-------------------->>>>>>>>>>>>>>>>>>>>>>>>>>1"
              apt-get install apt-transport-https
              echo "<<<<<<<<<<<<<<<<<<<<<-------------------->>>>>>>>>>>>>>>>>>>>>>>>>>2"
              sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
              echo "<<<<<<<<<<<<<<<<<<<<<-------------------->>>>>>>>>>>>>>>>>>>>>>>>>>3"
              apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
              echo "<<<<<<<<<<<<<<<<<<<<<-------------------->>>>>>>>>>>>>>>>>>>>>>>>>>4"
              apt-get install dotnet-sdk-2.0.2
              echo "<<<<<<<<<<<<<<<<<<<<<-------------------->>>>>>>>>>>>>>>>>>>>>>>>>>5"
      - run: 
          command: |
               dotnet restore
               dotnet build
               dotnet publish -o publish
      - run: echo "no tests 2"
